// SPDX-License-Identifier: GPL-2.0
/* ===========================================================================
 * xdp_loader.c — the userspace control plane: load, attach, configure, report.
 * ===========================================================================
 *
 * This is an ordinary Linux process (built for the host, with libbpf). Its jobs:
 *
 *   1. LOAD the compiled BPF object into the kernel and let the verifier check
 *      it. We use a libbpf "skeleton" (xdp_filter.skel.h, generated by
 *      `bpftool gen skeleton`) which turns the .bpf.o into a typed C API:
 *      open -> configure -> load -> attach, with every map and program reachable
 *      as skel->maps.NAME / skel->progs.NAME. This is CO-RE (Compile Once, Run
 *      Everywhere): the same .bpf.o binary loads on many kernel versions because
 *      libbpf relocates it against the running kernel's BTF at load time.
 *
 *   2. CONFIGURE the data plane before it starts: set the rodata `drop_all_icmp`
 *      flag, and fill the blocklist map from --block arguments. Because the
 *      blocklist is a map, we can add/remove blocked IPs at runtime WITHOUT
 *      touching the running program — the data/control-plane split in action.
 *
 *   3. ATTACH the program to a NIC's XDP hook (by ifindex).
 *
 *   4. REPORT: every interval, read the stats maps and print them. Reading a
 *      PER-CPU map returns one value PER CPU; userspace must sum them — the
 *      program never does, on purpose, to stay lock-free on the hot path.
 *
 *   5. DETACH cleanly on Ctrl-C. If we leaked the attachment, the NIC would keep
 *      running our filter after we exit — a footgun the skeleton's destructor
 *      and our link handle prevent.
 *
 * Build & run are in the README. This file compiles on the host but only *runs*
 * on Linux with CAP_BPF/CAP_NET_ADMIN (i.e. under sudo, in a QEMU VM).
 * ===========================================================================
 */

#include <argp.h>		/* not used heavily; kept minimal below         */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <net/if.h>		/* if_nametoindex(): NIC name -> ifindex         */
#include <arpa/inet.h>		/* inet_pton/inet_ntop for IPv4 text <-> bytes   */
#include <bpf/libbpf.h>		/* libbpf: skeleton runtime, bpf_program__*      */
#include <bpf/bpf.h>		/* low-level map syscalls: bpf_map_lookup_elem   */

/* The skeleton is GENERATED at build time from xdp_filter.bpf.o. It defines
 * struct xdp_filter (the skeleton), xdp_filter__open/load/attach/destroy, and
 * typed handles skel->maps.* / skel->progs.* / skel->rodata->*. See the Makefile
 * rule that runs `bpftool gen skeleton`. */
#include "xdp_filter.skel.h"

/* Shared key/value/index definitions — the SAME header the BPF program includes,
 * so our struct datarec and enum proto_idx match the kernel side exactly. */
#include "xdp_filter.h"

/* ---------------------------------------------------------------------------
 * libbpf routes its diagnostics through a callback. Installing one lets us see
 * verifier output — which is where you live when a program is rejected. We print
 * everything at or above WARN; flip to LIBBPF_DEBUG while debugging a load. */
static int libbpf_print_fn(enum libbpf_print_level level,
			   const char *format, va_list args)
{
	if (level == LIBBPF_DEBUG)
		return 0;		/* suppress the very chatty debug stream */
	return vfprintf(stderr, format, args);
}

/* SIGINT/SIGTERM flip this; the main loop polls it so we tear down cleanly
 * instead of leaving the XDP program attached to the NIC. `volatile sig_atomic_t`
 * is the only type the C standard promises is safe to touch from a handler. */
static volatile sig_atomic_t exiting = 0;
static void on_signal(int sig) { (void)sig; exiting = 1; }

/* Human-readable names for the per-protocol array rows, indexed by enum
 * proto_idx. Kept adjacent to the enum's meaning so a new row is obvious. */
static const char *proto_name[PROTO_IDX__MAX] = {
	[PROTO_IDX_OTHER] = "other",
	[PROTO_IDX_TCP]   = "tcp",
	[PROTO_IDX_UDP]   = "udp",
	[PROTO_IDX_ICMP]  = "icmp",
};

/* Names for the XDP verdicts, indexed by action code (XDP_ABORTED..REDIRECT). */
static const char *action_name[XDP_ACTION_MAX] = {
	[XDP_ABORTED]  = "ABORTED",
	[XDP_DROP]     = "DROP",
	[XDP_PASS]     = "PASS",
	[XDP_TX]       = "TX",
	[XDP_REDIRECT] = "REDIRECT",
};

/* ---------------------------------------------------------------------------
 * sum_percpu — read one entry of a PER-CPU array map and fold the CPUs together.
 *
 * A per-CPU map stores nr_cpus independent copies of the value. The kernel hands
 * them all back in a flat array on lookup, so our buffer must be sized
 * nr_cpus * sizeof(struct datarec). We sum packets and bytes across CPUs to get
 * the global total. Doing the fold HERE, in the slow path, is exactly why the
 * data plane could stay atomic-free — we moved the cost off the hot path. */
static int sum_percpu(int map_fd, __u32 key, unsigned nr_cpus,
		      struct datarec *out)
{
	/* One datarec per possible CPU. VLA sized by nr_cpus (small, bounded). */
	struct datarec values[nr_cpus];
	memset(out, 0, sizeof(*out));

	if (bpf_map_lookup_elem(map_fd, &key, values) != 0)
		return -errno;		/* key absent or map error               */

	for (unsigned c = 0; c < nr_cpus; c++) {
		out->packets += values[c].packets;
		out->bytes   += values[c].bytes;
	}
	return 0;
}

/* Pretty-print a byte count with a binary unit so a firehose is readable. */
static void human_bytes(char *buf, size_t n, __u64 bytes)
{
	const char *u[] = { "B", "KiB", "MiB", "GiB", "TiB" };
	double v = (double)bytes;
	int i = 0;
	while (v >= 1024.0 && i < 4) { v /= 1024.0; i++; }
	snprintf(buf, n, "%.1f %s", v, u[i]);
}

/* ---------------------------------------------------------------------------
 * dump_stats — one full report: verdicts, protocols, LB buckets, top talkers,
 * and the blocklist. Called once per interval and once more at shutdown.
 * --------------------------------------------------------------------------- */
static void dump_stats(struct xdp_filter *skel, unsigned nr_cpus)
{
	char bbuf[32];
	struct datarec d;

	printf("\n==================== XDP filter stats ====================\n");

	/* --- verdict histogram (per-CPU array keyed by action code) --- */
	printf("Verdicts:\n");
	int fd = bpf_map__fd(skel->maps.xdp_action_map);
	for (__u32 a = 0; a < XDP_ACTION_MAX; a++) {
		if (sum_percpu(fd, a, nr_cpus, &d) != 0)
			continue;
		if (d.packets == 0)
			continue;
		human_bytes(bbuf, sizeof(bbuf), d.bytes);
		printf("  %-9s %12llu pkts  %12s\n",
		       action_name[a], (unsigned long long)d.packets, bbuf);
	}

	/* --- per-protocol (per-CPU array keyed by proto_idx) --- */
	printf("Protocols:\n");
	fd = bpf_map__fd(skel->maps.proto_map);
	for (__u32 p = 0; p < PROTO_IDX__MAX; p++) {
		if (sum_percpu(fd, p, nr_cpus, &d) != 0)
			continue;
		if (d.packets == 0)
			continue;
		human_bytes(bbuf, sizeof(bbuf), d.bytes);
		printf("  %-9s %12llu pkts  %12s\n",
		       proto_name[p], (unsigned long long)d.packets, bbuf);
	}

	/* --- load-balancer bucket distribution (per-CPU array) ---
	 * If the flow hash is uniform, these counts should be roughly equal for a
	 * diverse traffic mix. Skew here means either biased traffic or a bad hash
	 * — the reason we visualise it at all. */
	printf("LB buckets (flow-hash distribution):\n");
	fd = bpf_map__fd(skel->maps.lb_bucket_map);
	for (__u32 b = 0; b < LB_BUCKETS; b++) {
		if (sum_percpu(fd, b, nr_cpus, &d) != 0)
			continue;
		printf("  bucket %u: %10llu pkts\n",
		       b, (unsigned long long)d.packets);
	}

	/* --- top talkers (LRU HASH keyed by source IPv4) ---
	 * Iterate the hash with the get-next-key walk: start from a NULL key to
	 * get the first, then feed each key back to advance. The value for a HASH
	 * (not per-CPU) is a single struct, no summing needed. */
	printf("Top talkers (per source IP):\n");
	fd = bpf_map__fd(skel->maps.src_map);
	__u32 key = 0, next = 0;
	int have_key = 0;			/* 0 => pass NULL to get the first */
	while (bpf_map_get_next_key(fd, have_key ? &key : NULL, &next) == 0) {
		struct datarec sd;
		if (bpf_map_lookup_elem(fd, &next, &sd) == 0) {
			char ip[INET_ADDRSTRLEN];
			/* `next` is the source IP in NETWORK byte order, exactly as
			 * the packet carried it, so inet_ntop consumes it directly. */
			inet_ntop(AF_INET, &next, ip, sizeof(ip));
			human_bytes(bbuf, sizeof(bbuf), sd.bytes);
			printf("  %-15s %12llu pkts  %12s\n",
			       ip, (unsigned long long)sd.packets, bbuf);
		}
		key = next;
		have_key = 1;
	}

	/* --- blocklist and how many packets each entry has dropped --- */
	printf("Blocklist (dropped per source IP):\n");
	fd = bpf_map__fd(skel->maps.blocklist_map);
	have_key = 0;
	while (bpf_map_get_next_key(fd, have_key ? &key : NULL, &next) == 0) {
		__u64 cnt = 0;
		if (bpf_map_lookup_elem(fd, &next, &cnt) == 0) {
			char ip[INET_ADDRSTRLEN];
			inet_ntop(AF_INET, &next, ip, sizeof(ip));
			printf("  %-15s %12llu dropped\n",
			       ip, (unsigned long long)cnt);
		}
		key = next;
		have_key = 1;
	}
	fflush(stdout);
}

/* ---------------------------------------------------------------------------
 * Tiny hand-rolled argument parsing (no external deps beyond libc). Usage:
 *   xdp_loader <ifname> [-i] [-t secs] [-b A.B.C.D ]...
 *     <ifname>   NIC to attach XDP to (e.g. eth0). REQUIRED.
 *     -i         set drop_all_icmp=1 (drop every ICMP packet)
 *     -t secs    report interval (default 2)
 *     -b IP      add IPv4 to the source blocklist (repeatable, up to 64 here)
 * --------------------------------------------------------------------------- */
#define MAX_BLOCK 64
struct cli {
	const char *ifname;
	int   drop_icmp;
	int   interval;
	__u32 block[MAX_BLOCK];	/* network-order IPs to block */
	int   nblock;
};

static int parse_args(int argc, char **argv, struct cli *c)
{
	c->ifname = NULL;
	c->drop_icmp = 0;
	c->interval = 2;
	c->nblock = 0;

	for (int i = 1; i < argc; i++) {
		if (strcmp(argv[i], "-i") == 0) {
			c->drop_icmp = 1;
		} else if (strcmp(argv[i], "-t") == 0 && i + 1 < argc) {
			c->interval = atoi(argv[++i]);
			if (c->interval <= 0)
				c->interval = 2;
		} else if (strcmp(argv[i], "-b") == 0 && i + 1 < argc) {
			if (c->nblock >= MAX_BLOCK) {
				fprintf(stderr, "too many -b entries (max %d)\n",
					MAX_BLOCK);
				return -1;
			}
			/* inet_pton writes the address in NETWORK byte order, which
			 * is exactly what the BPF side compares ip->saddr against. */
			__u32 a;
			if (inet_pton(AF_INET, argv[++i], &a) != 1) {
				fprintf(stderr, "bad IPv4: %s\n", argv[i]);
				return -1;
			}
			c->block[c->nblock++] = a;
		} else if (argv[i][0] != '-' && !c->ifname) {
			c->ifname = argv[i];	/* first non-flag = interface */
		} else {
			fprintf(stderr, "unknown/!misplaced arg: %s\n", argv[i]);
			return -1;
		}
	}
	if (!c->ifname) {
		fprintf(stderr,
			"usage: %s <ifname> [-i] [-t secs] [-b IP]...\n", argv[0]);
		return -1;
	}
	return 0;
}

int main(int argc, char **argv)
{
	struct cli cli;
	if (parse_args(argc, argv, &cli) != 0)
		return 1;

	/* Resolve the NIC name to its kernel ifindex. XDP attaches by ifindex, not
	 * by name — the name is just a userspace label for the index. 0 => no such
	 * interface. */
	unsigned int ifindex = if_nametoindex(cli.ifname);
	if (ifindex == 0) {
		fprintf(stderr, "no such interface '%s': %s\n",
			cli.ifname, strerror(errno));
		return 1;
	}

	libbpf_set_print(libbpf_print_fn);

	/* How many per-CPU slots each per-CPU map value has. MUST match what the
	 * kernel used to size the value on lookup, or we misread the buffer. */
	int nr = libbpf_num_possible_cpus();
	if (nr < 0) {
		fprintf(stderr, "libbpf_num_possible_cpus failed\n");
		return 1;
	}
	unsigned nr_cpus = (unsigned)nr;

	/* --- OPEN: parse the embedded .bpf.o, build maps/progs in memory, but do
	 * NOT load into the kernel yet. This is the window in which we may patch
	 * rodata, because after load() the read-only section is frozen. --- */
	struct xdp_filter *skel = xdp_filter__open();
	if (!skel) {
		fprintf(stderr, "failed to open BPF skeleton\n");
		return 1;
	}

	/* Set the compile-time-constant flag the program reads. Writing it here,
	 * before load, lets the verifier treat it as a literal and dead-code-strip
	 * the ICMP branch when it is 0. After load this write would be ignored. */
	skel->rodata->drop_all_icmp = cli.drop_icmp ? 1 : 0;

	/* --- LOAD: hand the bytecode to the kernel; the VERIFIER runs here. A
	 * rejection shows up as a negative return plus a verifier log via our print
	 * callback. libbpf also auto-raises RLIMIT_MEMLOCK for us on modern
	 * versions, so we don't setrlimit by hand. --- */
	if (xdp_filter__load(skel)) {
		fprintf(stderr, "failed to load/verify BPF program\n");
		goto cleanup;
	}

	/* --- Fill the blocklist BEFORE attaching so no packet slips past unblocked
	 * during the race between attach and the first map update. Value seeds the
	 * per-IP drop counter at 0. --- */
	int bl_fd = bpf_map__fd(skel->maps.blocklist_map);
	for (int i = 0; i < cli.nblock; i++) {
		__u64 zero = 0;
		if (bpf_map_update_elem(bl_fd, &cli.block[i], &zero, BPF_ANY) != 0) {
			fprintf(stderr, "warn: could not add block entry %d: %s\n",
				i, strerror(errno));
		}
	}

	/* --- ATTACH to the NIC's XDP hook. bpf_program__attach_xdp installs the
	 * program at the driver hook for `ifindex` and returns a LINK handle whose
	 * lifetime IS the attachment: destroying it (or the process exiting) detaches
	 * cleanly. On a driver without native XDP this falls back to generic/SKB-mode
	 * XDP (slower, runs after sk_buff alloc) — fine for a demo, and the kernel
	 * tells you which mode you got. --- */
	struct bpf_link *link =
		bpf_program__attach_xdp(skel->progs.xdp_filter_prog, ifindex);
	if (!link) {
		fprintf(stderr, "attach to %s (ifindex %u) failed: %s\n"
			"  (need CAP_NET_ADMIN/root; try native driver or run in a VM)\n",
			cli.ifname, ifindex, strerror(errno));
		goto cleanup;
	}

	signal(SIGINT, on_signal);
	signal(SIGTERM, on_signal);

	printf("attached xdp_filter to %s (ifindex %u), drop_icmp=%d, "
	       "blocklist=%d entries, %u CPUs\n"
	       "reporting every %ds; Ctrl-C to detach.\n",
	       cli.ifname, ifindex, cli.drop_icmp, cli.nblock, nr_cpus,
	       cli.interval);

	/* --- REPORT LOOP. sleep() returns early if a signal arrives, so Ctrl-C
	 * breaks out promptly. --- */
	while (!exiting) {
		sleep(cli.interval);
		dump_stats(skel, nr_cpus);
	}

	printf("\ndetaching...\n");
	dump_stats(skel, nr_cpus);		/* final snapshot */

	/* Destroying the link detaches the program from the NIC. */
	bpf_link__destroy(link);

cleanup:
	/* Frees maps, programs, and unloads the BPF object from the kernel. */
	xdp_filter__destroy(skel);
	return 0;
}
