/* SPDX-License-Identifier: GPL-2.0 */
/* ===========================================================================
 * scx_fifo.c — the USERSPACE loader for the scx_fifo BPF scheduler.
 * ===========================================================================
 *
 * This program does four things and then gets out of the way:
 *   1. open   the compiled BPF object (via the libbpf skeleton generated by
 *             `bpftool gen skeleton`),
 *   2. configure it (set the `-f` FIFO flag into the read-only .rodata BEFORE
 *             load, so the verifier can constant-fold it),
 *   3. load + attach the struct_ops object — the ATTACH is the instant our BPF
 *             code becomes the machine's live CPU scheduler,
 *   4. loop, printing per-CPU stats once a second, until Ctrl-C or until the
 *             kernel ejects the scheduler (watchdog / verifier / error).
 *
 * IMPORTANT: while this process holds the attach link, EVERY normal task on the
 * box is scheduled by our BPF program. The moment this process exits — for any
 * reason, including being killed — the link drops, the kernel tears the
 * scheduler down, and EEVDF resumes. That "unload on exit" property is a
 * deliberate safety feature: you cannot leave a broken scheduler wedged in.
 *
 * The heavy lifting hides behind the SCX_OPS_* and UEI_* macros from
 * <scx/common.h> (kernel tree tools/sched_ext/include, or the sched-ext/scx
 * repo). Each one is explained where it is used below.
 * =========================================================================== */

#include <stdio.h>
#include <unistd.h>
#include <signal.h>
#include <libgen.h>
#include <string.h>
#include <bpf/bpf.h>
#include <scx/common.h>
/* Generated at build time by `bpftool gen skeleton scx_fifo.bpf.o`. It gives us
 * a typed `struct scx_fifo` handle with ->rodata (our fifo_sched flag),
 * ->bss (the uei exit-info), ->maps (the stats map), and ->struct_ops (the
 * fifo_ops table) — no manual FD juggling required. */
#include "scx_fifo.bpf.skel.h"

static const char help_fmt[] =
"A teaching sched_ext scheduler: global FIFO or weighted virtual-time.\n"
"\n"
"Usage: %s [-f] [-v]\n"
"\n"
"  -f            Strict global FIFO (default is weighted-vtime fair-share)\n"
"  -v            Verbose libbpf logging (shows the verifier's work)\n"
"  -h            This help\n";

/* Set from the SIGINT/SIGTERM handler. `volatile` because it is written from a
 * signal handler and read in the main loop — the compiler must re-read it from
 * memory each iteration rather than caching it in a register. */
static volatile int exit_req;
static bool verbose;

/* libbpf routes all its logging through this. We swallow DEBUG spam unless -v,
 * so a normal run is quiet but `-v` shows the verifier accepting each program —
 * invaluable when a scheduler fails to load. */
static int libbpf_print_fn(enum libbpf_print_level level, const char *format,
			   va_list args)
{
	if (level == LIBBPF_DEBUG && !verbose)
		return 0;
	return vfprintf(stderr, format, args);
}

static void sigint_handler(int sig)
{
	exit_req = 1;	/* ask the main loop to fall through to teardown */
}

/* Sum the PERCPU stats map into two totals. Each CPU has its own [local, global]
 * pair (no shared cache line, no atomics in the BPF side); the kernel hands us
 * back one value PER possible CPU per index, and we add them up here. This is
 * the standard way to read a BPF_MAP_TYPE_PERCPU_ARRAY from userspace. */
static void read_stats(struct scx_fifo *skel, __u64 *stats)
{
	int nr_cpus = libbpf_num_possible_cpus();
	__u64 cnts[2][nr_cpus];
	__u32 idx;

	memset(stats, 0, sizeof(stats[0]) * 2);

	for (idx = 0; idx < 2; idx++) {
		int ret, cpu;

		/* One lookup returns the value for ALL CPUs at this index, into
		 * cnts[idx][0..nr_cpus-1]. */
		ret = bpf_map_lookup_elem(bpf_map__fd(skel->maps.stats),
					  &idx, cnts[idx]);
		if (ret < 0)
			continue;	/* map not ready yet; skip this tick */
		for (cpu = 0; cpu < nr_cpus; cpu++)
			stats[idx] += cnts[idx][cpu];
	}
}

int main(int argc, char **argv)
{
	struct scx_fifo *skel;
	struct bpf_link *link;
	__u32 opt;
	__u64 ecode;

	/* Wire libbpf's logger and install signal handlers so Ctrl-C unwinds
	 * cleanly (which unloads the scheduler) instead of leaving it attached. */
	libbpf_set_print(libbpf_print_fn);
	signal(SIGINT, sigint_handler);
	signal(SIGTERM, sigint_handler);
restart:
	/* SCX_OPS_OPEN(ops, skel_type): open the skeleton and sanity-check that
	 * the running kernel actually supports the ops we reference. Returns the
	 * skeleton; on failure it aborts with a clear message (usually "your
	 * kernel lacks CONFIG_SCHED_CLASS_EXT" or "too old"). */
	skel = SCX_OPS_OPEN(fifo_ops, scx_fifo);

	/* Parse flags AFTER open but BEFORE load: fifo_sched lives in .rodata,
	 * which is frozen at load time. Setting it now lets the verifier treat
	 * the `if (fifo_sched)` branches in the BPF program as compile-time
	 * constants and prune the dead policy entirely. */
	while ((opt = getopt(argc, argv, "fvh")) != -1) {
		switch (opt) {
		case 'f':
			skel->rodata->fifo_sched = true;
			break;
		case 'v':
			verbose = true;
			break;
		default:
			fprintf(stderr, help_fmt, basename(argv[0]));
			return opt != 'h';
		}
	}

	/* SCX_OPS_LOAD: run the verifier over every program and load them into
	 * the kernel. If the verifier rejects the scheduler, this aborts here —
	 * nothing is attached, the machine's scheduler is untouched. */
	SCX_OPS_LOAD(skel, fifo_ops, scx_fifo, uei);

	/* SCX_OPS_ATTACH: the pivotal call. It attaches the struct_ops object,
	 * and at that instant the kernel switches every SCHED_NORMAL task onto
	 * OUR scheduler. The returned link keeps it attached; dropping the link
	 * (or exiting) detaches and restores EEVDF. */
	link = SCX_OPS_ATTACH(skel, fifo_ops, scx_fifo);

	/* Supervise. UEI_EXITED becomes true if the kernel unloaded us — e.g.
	 * the watchdog fired because a task was starved too long, or a runtime
	 * error occurred. Otherwise we run until the operator hits Ctrl-C. */
	while (!exit_req && !UEI_EXITED(skel, uei)) {
		__u64 stats[2];

		read_stats(skel, stats);
		/* local  = tasks placed on a CPU-local DSQ via the select_cpu
		 *          idle fast path.
		 * global = tasks that went through enqueue() onto the shared
		 *          DSQ. Watch the ratio shift as you change the load:
		 *          an under-committed box is mostly `local`; a saturated
		 *          one is mostly `global`. */
		printf("local=%llu global=%llu\n",
		       (unsigned long long)stats[0], (unsigned long long)stats[1]);
		fflush(stdout);
		sleep(1);
	}

	/* Clean teardown: drop the link (detaches the scheduler), report why we
	 * exited (UEI_REPORT prints the kernel's exit reason if it ejected us),
	 * and free the skeleton. */
	bpf_link__destroy(link);
	ecode = UEI_REPORT(skel, uei);
	scx_fifo__destroy(skel);

	/* Some SCX exit codes mean "restart me" (e.g. the CPU topology changed
	 * under us). Honour that by looping back to a fresh open/load/attach. */
	if (UEI_ECODE_RESTART(ecode))
		goto restart;
	return 0;
}
